### ISSUE TITLE
Greetings. Good to find this analyzer.

### ISSUE THREAD

**Issue by baicaigithub** [appcell/OverwatchDataAnalysis#53]
Not sure if it is okay to use issues to say hi. Thank you so much for starting this project.

I am an OW fan and would love to use this tool to analyze my 1st person recording. Though this may not be a goal for the project for now, I would like to contribute to the project. Let me know what you think. Thanks!

**Comment by appcell** [comment]
Hello Baicai, it would be really nice to have someone joining us for 1st person recordings!! We currently don't have a plan for it since we found it kinda difficult, but I'm sure you'll bring new ideas.
You can contact me at appcell@outlook.com. I'm really looking forward to hear about your thoughts!

**Comment by baicaigithub** [comment]
Got the killfeed works for 1st person recording. Will clean it up a bit.

**Comment by appcell** [comment]
Hey can you contact me with email?
